export const predefinedGenres = [
    "Fiction",
    "Non-Fiction",
    "Mystery",
    "Thriller",
    "Romance",
    "Fantasy",
    "Science Fiction",
    "Horror",
    "Biography",
    "History",
    "Self-Help",
    "Business",
    "Health",
    "Travel",
    "Cooking",
    "Art",
    "Poetry",
    "Drama",
    "Adventure",
    "Young Adult",
    "Children",
    "Comedy",
    "Crime",
    "Philosophy",
    "Psychology",
    "Religion",
    "Politics",
    "Technology",
    "Education",
  ];