export const GENRE_OPTIONS = [
  { value: "mystery", label: "Mystery" },
  { value: "thriller", label: "Thriller" },
  { value: "romance", label: "Romance" },
  { value: "fantasy", label: "Fantasy" },
  { value: "science", label: "Science" },
  { value: "horror", label: "Horror" },
  { value: "biography", label: "Biography" },
  { value: "history", label: "History" },
  { value: "self-help", label: "Self-Help" },
  { value: "business", label: "Business" },
  { value: "health", label: "Health" },
  { value: "travel", label: "Travel" },
  { value: "cooking", label: "Cooking" },
  { value: "art", label: "Art" },
  { value: "poetry", label: "Poetry" },
  { value: "drama", label: "Drama" },
  { value: "adventure", label: "Adventure" },
  { value: "children", label: "Children" },
  { value: "comedy", label: "Comedy" },
  { value: "crime", label: "Crime" },
  { value: "philosophy", label: "Philosophy" },
  { value: "psychology", label: "Psychology" },
  { value: "religion", label: "Religion" },
  { value: "politics", label: "Politics" },
  { value: "technology", label: "Technology" },
  { value: "education", label: "Education" },
];

export const SORT_OPTIONS = [
  { value: "title-asc", label: "Title (A-Z)" },
  { value: "title-desc", label: "Title (Z-A)" },
  { value: "year-desc", label: "Added date (Newest)" },
  { value: "year-asc", label: "Added date (Oldest)" },
];
